
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Probs : Luban.BeanBase
{
    public Probs(JSONNode _buf) 
    {
        { if(!_buf["prob_lv"].IsNumber) { throw new SerializationException(); }  ProbLv = _buf["prob_lv"]; }
        { if(!_buf["lv0"].IsNumber) { throw new SerializationException(); }  Lv0 = _buf["lv0"]; }
        { if(!_buf["lv1"].IsNumber) { throw new SerializationException(); }  Lv1 = _buf["lv1"]; }
        { if(!_buf["lv2"].IsNumber) { throw new SerializationException(); }  Lv2 = _buf["lv2"]; }
        { if(!_buf["lv3"].IsNumber) { throw new SerializationException(); }  Lv3 = _buf["lv3"]; }
    }

    public static Probs DeserializeProbs(JSONNode _buf)
    {
        return new Probs(_buf);
    }

    public readonly int ProbLv;
    public readonly float Lv0;
    public readonly float Lv1;
    public readonly float Lv2;
    public readonly float Lv3;
   
    public const int __ID__ = 77387678;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "probLv:" + ProbLv + ","
        + "lv0:" + Lv0 + ","
        + "lv1:" + Lv1 + ","
        + "lv2:" + Lv2 + ","
        + "lv3:" + Lv3 + ","
        + "}";
    }
}

}
