
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Audio : Luban.BeanBase
{
    public Audio(JSONNode _buf) 
    {
        { if(!_buf["enter_btn"].IsString) { throw new SerializationException(); }  EnterBtn = _buf["enter_btn"]; }
        { if(!_buf["click_btn"].IsString) { throw new SerializationException(); }  ClickBtn = _buf["click_btn"]; }
        { if(!_buf["click_tgl"].IsString) { throw new SerializationException(); }  ClickTgl = _buf["click_tgl"]; }
        { if(!_buf["drag_bar_music"].IsString) { throw new SerializationException(); }  DragBarMusic = _buf["drag_bar_music"]; }
        { if(!_buf["drag_bar_sfx"].IsString) { throw new SerializationException(); }  DragBarSfx = _buf["drag_bar_sfx"]; }
        { if(!_buf["main_menu_bgm"].IsString) { throw new SerializationException(); }  MainMenuBgm = _buf["main_menu_bgm"]; }
        { if(!_buf["game_bgm"].IsString) { throw new SerializationException(); }  GameBgm = _buf["game_bgm"]; }
        { if(!_buf["pop_out"].IsString) { throw new SerializationException(); }  PopOut = _buf["pop_out"]; }
        { if(!_buf["pop_move"].IsString) { throw new SerializationException(); }  PopMove = _buf["pop_move"]; }
        { if(!_buf["pop_hide"].IsString) { throw new SerializationException(); }  PopHide = _buf["pop_hide"]; }
        { if(!_buf["slide_up"].IsString) { throw new SerializationException(); }  SlideUp = _buf["slide_up"]; }
        { if(!_buf["slide_down"].IsString) { throw new SerializationException(); }  SlideDown = _buf["slide_down"]; }
        { if(!_buf["count_down"].IsString) { throw new SerializationException(); }  CountDown = _buf["count_down"]; }
        { if(!_buf["laugh_1"].IsString) { throw new SerializationException(); }  Laugh1 = _buf["laugh_1"]; }
        { if(!_buf["laugh_2"].IsString) { throw new SerializationException(); }  Laugh2 = _buf["laugh_2"]; }
        { if(!_buf["laugh_3"].IsString) { throw new SerializationException(); }  Laugh3 = _buf["laugh_3"]; }
        { if(!_buf["laugh_4"].IsString) { throw new SerializationException(); }  Laugh4 = _buf["laugh_4"]; }
        { if(!_buf["click_button"].IsString) { throw new SerializationException(); }  ClickButton = _buf["click_button"]; }
        { if(!_buf["buzzer"].IsString) { throw new SerializationException(); }  Buzzer = _buf["buzzer"]; }
    }

    public static Audio DeserializeAudio(JSONNode _buf)
    {
        return new Audio(_buf);
    }

    /// <summary>
    /// 按钮_悬停
    /// </summary>
    public readonly string EnterBtn;
    /// <summary>
    /// 按钮_点击
    /// </summary>
    public readonly string ClickBtn;
    /// <summary>
    /// 切换_点击
    /// </summary>
    public readonly string ClickTgl;
    /// <summary>
    /// 进度条_拖拽_测试音乐
    /// </summary>
    public readonly string DragBarMusic;
    /// <summary>
    /// 进度条_拖拽_测试音效
    /// </summary>
    public readonly string DragBarSfx;
    /// <summary>
    /// 主菜单_背景乐
    /// </summary>
    public readonly string MainMenuBgm;
    /// <summary>
    /// 游戏_背景乐
    /// </summary>
    public readonly string GameBgm;
    /// <summary>
    /// 弹窗_弹出
    /// </summary>
    public readonly string PopOut;
    /// <summary>
    /// 弹窗_移动
    /// </summary>
    public readonly string PopMove;
    /// <summary>
    /// 弹窗_隐藏
    /// </summary>
    public readonly string PopHide;
    /// <summary>
    /// 上划
    /// </summary>
    public readonly string SlideUp;
    /// <summary>
    /// 下划
    /// </summary>
    public readonly string SlideDown;
    /// <summary>
    /// 倒计时
    /// </summary>
    public readonly string CountDown;
    /// <summary>
    /// 笑
    /// </summary>
    public readonly string Laugh1;
    /// <summary>
    /// 欢呼
    /// </summary>
    public readonly string Laugh2;
    /// <summary>
    /// 大声欢呼
    /// </summary>
    public readonly string Laugh3;
    /// <summary>
    /// 满堂喝彩
    /// </summary>
    public readonly string Laugh4;
    /// <summary>
    /// 按钮
    /// </summary>
    public readonly string ClickButton;
    /// <summary>
    /// 蜂鸣器
    /// </summary>
    public readonly string Buzzer;
   
    public const int __ID__ = 63613878;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "enterBtn:" + EnterBtn + ","
        + "clickBtn:" + ClickBtn + ","
        + "clickTgl:" + ClickTgl + ","
        + "dragBarMusic:" + DragBarMusic + ","
        + "dragBarSfx:" + DragBarSfx + ","
        + "mainMenuBgm:" + MainMenuBgm + ","
        + "gameBgm:" + GameBgm + ","
        + "popOut:" + PopOut + ","
        + "popMove:" + PopMove + ","
        + "popHide:" + PopHide + ","
        + "slideUp:" + SlideUp + ","
        + "slideDown:" + SlideDown + ","
        + "countDown:" + CountDown + ","
        + "laugh1:" + Laugh1 + ","
        + "laugh2:" + Laugh2 + ","
        + "laugh3:" + Laugh3 + ","
        + "laugh4:" + Laugh4 + ","
        + "clickButton:" + ClickButton + ","
        + "buzzer:" + Buzzer + ","
        + "}";
    }
}

}
