
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardParas : Luban.BeanBase
{
    public CardParas(JSONNode _buf) 
    {
        { var __json0 = _buf["para0"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Para0 = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Para0[__index0++] = __v0; }   }
        { var __json0 = _buf["para1"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Para1 = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Para1[__index0++] = __v0; }   }
        { var __json0 = _buf["para2"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Para2 = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Para2[__index0++] = __v0; }   }
        { var __json0 = _buf["para3"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Para3 = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Para3[__index0++] = __v0; }   }
    }

    public static CardParas DeserializeCardParas(JSONNode _buf)
    {
        return new CardParas(_buf);
    }

    /// <summary>
    /// 稀有度0
    /// </summary>
    public readonly int[] Para0;
    /// <summary>
    /// 稀有度1
    /// </summary>
    public readonly int[] Para1;
    /// <summary>
    /// 稀有度2
    /// </summary>
    public readonly int[] Para2;
    /// <summary>
    /// 稀有度3
    /// </summary>
    public readonly int[] Para3;
   
    public const int __ID__ = 1744516931;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "para0:" + Luban.StringUtil.CollectionToString(Para0) + ","
        + "para1:" + Luban.StringUtil.CollectionToString(Para1) + ","
        + "para2:" + Luban.StringUtil.CollectionToString(Para2) + ","
        + "para3:" + Luban.StringUtil.CollectionToString(Para3) + ","
        + "}";
    }
}

}
