
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardProbs : Luban.BeanBase
{
    public CardProbs(JSONNode _buf) 
    {
        { if(!_buf["prob_lv"].IsNumber) { throw new SerializationException(); }  ProbLv = _buf["prob_lv"]; }
        { var __json0 = _buf["probs"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Probs = new float[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Probs[__index0++] = __v0; }   }
    }

    public static CardProbs DeserializeCardProbs(JSONNode _buf)
    {
        return new CardProbs(_buf);
    }

    /// <summary>
    /// 发卡轮次
    /// </summary>
    public readonly int ProbLv;
    /// <summary>
    /// 稀有度0
    /// </summary>
    public readonly float[] Probs;
   
    public const int __ID__ = 1745020526;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "probLv:" + ProbLv + ","
        + "probs:" + Luban.StringUtil.CollectionToString(Probs) + ","
        + "}";
    }
}

}
