
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardSValue : Luban.BeanBase
{
    public CardSValue(JSONNode _buf) 
    {
        { var __json0 = _buf["point_ratio"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; PointRatio = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PointRatio[__index0++] = __v0; }   }
        { var __json0 = _buf["frame_res"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; FrameRes = new string[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  FrameRes[__index0++] = __v0; }   }
    }

    public static CardSValue DeserializeCardSValue(JSONNode _buf)
    {
        return new CardSValue(_buf);
    }

    /// <summary>
    /// 稀有度分数系数
    /// </summary>
    public readonly int[] PointRatio;
    /// <summary>
    /// 稀有度底框资源
    /// </summary>
    public readonly string[] FrameRes;
   
    public const int __ID__ = -1679316978;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "pointRatio:" + Luban.StringUtil.CollectionToString(PointRatio) + ","
        + "frameRes:" + Luban.StringUtil.CollectionToString(FrameRes) + ","
        + "}";
    }
}

}
