
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GameCard : Luban.BeanBase
{
    public GameCard(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["base_point"].IsNumber) { throw new SerializationException(); }  BasePoint = _buf["base_point"]; }
        { if(!_buf["card_des_key"].IsString) { throw new SerializationException(); }  CardDesKey = _buf["card_des_key"]; }
        { var __json0 = _buf["paras"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Paras = new int[_n0][]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int[] __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } int _n1 = __json1.Count; __v0 = new int[_n1]; int __index1=0; foreach(JSONNode __e1 in __json1.Children) { int __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0[__index1++] = __v1; }   }  Paras[__index0++] = __v0; }   }
        { if(!_buf["frame_res"].IsString) { throw new SerializationException(); }  FrameRes = _buf["frame_res"]; }
    }

    public static GameCard DeserializeGameCard(JSONNode _buf)
    {
        return new GameCard(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 基础分
    /// </summary>
    public readonly int BasePoint;
    /// <summary>
    /// 卡牌描述key
    /// </summary>
    public readonly string CardDesKey;
    /// <summary>
    /// 卡牌参数
    /// </summary>
    public readonly int[][] Paras;
    /// <summary>
    /// 卡面资源名
    /// </summary>
    public readonly string FrameRes;
   
    public const int __ID__ = -1705028030;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "basePoint:" + BasePoint + ","
        + "cardDesKey:" + CardDesKey + ","
        + "paras:" + Luban.StringUtil.CollectionToString(Paras) + ","
        + "frameRes:" + FrameRes + ","
        + "}";
    }
}

}
