
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbAudio TbAudio {get; }
    public TbL10nUI TbL10nUI {get; }
    public TbL10nGame TbL10nGame {get; }
    public TbUICard TbUICard {get; }
    public TbUICfg TbUICfg {get; }
    public TbGameCard TbGameCard {get; }
    public TbCardProbs TbCardProbs {get; }
    public TbCardSValue TbCardSValue {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbAudio = new TbAudio(loader("tbaudio"));
        TbL10nUI = new TbL10nUI(loader("tbl10nui"));
        TbL10nGame = new TbL10nGame(loader("tbl10ngame"));
        TbUICard = new TbUICard(loader("tbuicard"));
        TbUICfg = new TbUICfg(loader("tbuicfg"));
        TbGameCard = new TbGameCard(loader("tbgamecard"));
        TbCardProbs = new TbCardProbs(loader("tbcardprobs"));
        TbCardSValue = new TbCardSValue(loader("tbcardsvalue"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAudio.ResolveRef(this);
        TbL10nUI.ResolveRef(this);
        TbL10nGame.ResolveRef(this);
        TbUICard.ResolveRef(this);
        TbUICfg.ResolveRef(this);
        TbGameCard.ResolveRef(this);
        TbCardProbs.ResolveRef(this);
        TbCardSValue.ResolveRef(this);
    }
}

}
