
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbAudio
{

     private readonly Audio _data;

     public Audio Data => _data;

    public TbAudio(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = Audio.DeserializeAudio(_buf[0]);  }
    }


    /// <summary>
    /// 按钮_悬停
    /// </summary>
     public string EnterBtn => _data.EnterBtn;
    /// <summary>
    /// 按钮_点击
    /// </summary>
     public string ClickBtn => _data.ClickBtn;
    /// <summary>
    /// 切换_点击
    /// </summary>
     public string ClickTgl => _data.ClickTgl;
    /// <summary>
    /// 进度条_拖拽_测试音乐
    /// </summary>
     public string DragBarMusic => _data.DragBarMusic;
    /// <summary>
    /// 进度条_拖拽_测试音效
    /// </summary>
     public string DragBarSfx => _data.DragBarSfx;
    /// <summary>
    /// 主菜单_背景乐
    /// </summary>
     public string MainMenuBgm => _data.MainMenuBgm;
    /// <summary>
    /// 游戏_背景乐
    /// </summary>
     public string GameBgm => _data.GameBgm;
    /// <summary>
    /// 弹窗_弹出
    /// </summary>
     public string PopOut => _data.PopOut;
    /// <summary>
    /// 弹窗_移动
    /// </summary>
     public string PopMove => _data.PopMove;
    /// <summary>
    /// 弹窗_隐藏
    /// </summary>
     public string PopHide => _data.PopHide;
    /// <summary>
    /// 上划
    /// </summary>
     public string SlideUp => _data.SlideUp;
    /// <summary>
    /// 下划
    /// </summary>
     public string SlideDown => _data.SlideDown;
    /// <summary>
    /// 倒计时
    /// </summary>
     public string CountDown => _data.CountDown;
    /// <summary>
    /// 笑
    /// </summary>
     public string Laugh1 => _data.Laugh1;
    /// <summary>
    /// 欢呼
    /// </summary>
     public string Laugh2 => _data.Laugh2;
    /// <summary>
    /// 大声欢呼
    /// </summary>
     public string Laugh3 => _data.Laugh3;
    /// <summary>
    /// 满堂喝彩
    /// </summary>
     public string Laugh4 => _data.Laugh4;
    /// <summary>
    /// 按钮
    /// </summary>
     public string ClickButton => _data.ClickButton;
    /// <summary>
    /// 蜂鸣器
    /// </summary>
     public string Buzzer => _data.Buzzer;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

