
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbAudio
{
    private readonly System.Collections.Generic.Dictionary<string, Audio> _dataMap;
    private readonly System.Collections.Generic.List<Audio> _dataList;
    
    public TbAudio(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Audio>();
        _dataList = new System.Collections.Generic.List<Audio>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Audio _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Audio.DeserializeAudio(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EnterBtn, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Audio> DataMap => _dataMap;
    public System.Collections.Generic.List<Audio> DataList => _dataList;

    public Audio GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Audio Get(string key) => _dataMap[key];
    public Audio this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

