
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCardProbs
{
    private readonly System.Collections.Generic.Dictionary<int, CardProbs> _dataMap;
    private readonly System.Collections.Generic.List<CardProbs> _dataList;
    
    public TbCardProbs(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CardProbs>();
        _dataList = new System.Collections.Generic.List<CardProbs>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardProbs _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CardProbs.DeserializeCardProbs(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ProbLv, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CardProbs> DataMap => _dataMap;
    public System.Collections.Generic.List<CardProbs> DataList => _dataList;

    public CardProbs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardProbs Get(int key) => _dataMap[key];
    public CardProbs this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

