
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCardSValue
{
    private readonly System.Collections.Generic.List<CardSValue> _dataList;


    public TbCardSValue(JSONNode _buf)
    {
        _dataList = new System.Collections.Generic.List<CardSValue>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardSValue _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CardSValue.DeserializeCardSValue(_ele);  }
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<CardSValue> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

