
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCardSValue
{

     private readonly CardSValue _data;

     public CardSValue Data => _data;

    public TbCardSValue(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = CardSValue.DeserializeCardSValue(_buf[0]);  }
    }


    /// <summary>
    /// 稀有度分数系数
    /// </summary>
     public int[] PointRatio => _data.PointRatio;
    /// <summary>
    /// 稀有度底框资源
    /// </summary>
     public string[] FrameRes => _data.FrameRes;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

