
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbL10nUI
{
    private readonly System.Collections.Generic.Dictionary<string, L10nUI> _dataMap;
    private readonly System.Collections.Generic.List<L10nUI> _dataList;
    
    public TbL10nUI(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, L10nUI>();
        _dataList = new System.Collections.Generic.List<L10nUI>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            L10nUI _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = L10nUI.DeserializeL10nUI(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.L10nKey, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, L10nUI> DataMap => _dataMap;
    public System.Collections.Generic.List<L10nUI> DataList => _dataList;

    public L10nUI GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public L10nUI Get(string key) => _dataMap[key];
    public L10nUI this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

