
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class UICfg : Luban.BeanBase
{
    public UICfg(JSONNode _buf) 
    {
        { if(!_buf["menus"].IsString) { throw new SerializationException(); }  Menus = _buf["menus"]; }
        { var __json0 = _buf["cards"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Cards = new int[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Cards[__index0++] = __v0; }   }
    }

    public static UICfg DeserializeUICfg(JSONNode _buf)
    {
        return new UICfg(_buf);
    }

    /// <summary>
    /// 菜单
    /// </summary>
    public readonly string Menus;
    /// <summary>
    /// 该菜单下的卡牌
    /// </summary>
    public readonly int[] Cards;
   
    public const int __ID__ = 80741680;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "menus:" + Menus + ","
        + "cards:" + Luban.StringUtil.CollectionToString(Cards) + ","
        + "}";
    }
}

}
